### ISSUE TITLE
TRPO Agent not working for multi discrete action space

### ISSUE THREAD

**Issue by Akashg475** [Stable-Baselines-Team/stable-baselines3-contrib#83]
I am trying to implement TRPO agent for a custom environment with MultiDiscrete Action Space. But I am getting "NotImplementedError". The code and system are fine because same code is working for a Discrete Action Space.

    from gym import spaces, Env
    from sb3_contrib import TRPO
    import numpy as np
    
    class TestEnv(Env):
    
        def __init__(self):
    
            self.action_space = spaces.MultiDiscrete([2,2])
            # self.action_space = spaces.Discrete(4)
            self.observation_space = spaces.Box(low=np.array([0,0]), high=np.array([100,100]))
    
        def reset(self):
            return np.array([10,10]).astype(np.float32)
    
        def step(self, action):
            print(action)
    
            return np.array([10+action[0],10+action[1]]).astype(np.float32), -1, False, {}
            # return np.array([10+action//2,10+action%2]).astype(np.float32), -1, False, {}
    
    from stable_baselines3.common.env_checker import check_env
    
    train_env = TestEnv()
    check_env(train_env)
    
    model = TRPO('MlpPolicy', train_env,n_steps=5, batch_size=5)
    model.learn(2)

Output Error

    Traceback (most recent call last):
      File "/Users/akashgarg/Desktop/PycharmProjects/rlbaselinee_practice/Burger-Dog-AI/enjoy.py", line 27, in <module>
        model = TRPO('MlpPolicy', train_env,n_steps=5, batch_size=5)
      File "/Users/akashgarg/Desktop/PycharmProjects/rlbaselinee_practice/lib/python3.7/site-packages/sb3_contrib/trpo/trpo.py", line 426, in learn
        reset_num_timesteps=reset_num_timesteps,
      File "/Users/akashgarg/Desktop/PycharmProjects/rlbaselinee_practice/lib/python3.7/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 267, in learn
        self.train()
      File "/Users/akashgarg/Desktop/PycharmProjects/rlbaselinee_practice/lib/python3.7/site-packages/sb3_contrib/trpo/trpo.py", line 282, in train
        kl_div = kl_divergence(distribution.distribution, old_distribution.distribution).mean()
      File "/Users/akashgarg/Desktop/PycharmProjects/rlbaselinee_practice/lib/python3.7/site-packages/torch/distributions/kl.py", line 169, in kl_divergence
        raise NotImplementedError
    NotImplementedError

**System Info**
OS: Darwin-21.5.0-x86_64-i386-64bit Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
Python: 3.7.0
Stable-Baselines3: 1.5.1a7
PyTorch: 1.11.0
GPU Enabled: False
Numpy: 1.21.6
Gym: 0.21.0

**Comment by Miffyli** [comment]
Nice catch! Looking at how SB3 fixes this it uses [this](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/distributions.py#L677-L699) function to do kl_div, which has explicit check for "MultiDiscrete" spaces. Changing TRPO code to use this kl_div function instead of torch one will probably fix the issue. A PR to do so would be gladly accepted :)
